server:
  port: 8091

spring:
  application:
    name: car-service
  main:
    banner-mode: off
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password: password
  jpa:
    database-platform: H2
    generate-ddl: true

### Local
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password: password
  jpa:
    database-platform: H2
    generate-ddl: true

eureka:
  client:
    enabled: false

### Dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password: password
  jpa:
    database-platform: H2
    generate-ddl: true

eureka:
  client:
    serviceUrl:
      deafultZone: http://localhost:8761/eureka/
---

### Dev-Oracle
---
spring:
  config:
    activate:
      on-profile: dev-oracle
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: ${oracle.username}
    password: ${oracle.password}
eureka:
  client:
    serviceUrl:
      deafultZone: http://localhost:8761/eureka/
---